name:                dropbox
version:             0.0.4
license:             MIT
author:              "Riskbook"
maintainer:          "support@riskbook.com"
copyright:           "2020 Riskbook"
github:              "riskbook/dropbox-client"
synopsis:            Dropbox API client
description:         A dropbox API client generated through servant generic.
category:            API

extra-source-files:
- Readme.md
- LICENSE
- Changelog.md

ghc-options:
    - -Wall
    - -Wcompat
    - -Wincomplete-uni-patterns
    - -Wredundant-constraints
    - -Wincomplete-record-updates
    - -Widentities

dependencies:
- base >= 4.7 && < 4.15.0
- servant-client-core
- servant-client < 0.19
- servant-auth
- servant-auth-client
- http-api-data
- aeson
- servant
- http-client-tls
- text

library:
  source-dirs: src

executables:
  exe:
    main:                exe.hs
    source-dirs:         app
    dependencies:
    - dropbox
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N

tests:
  unit:
    main:                Spec.hs
    source-dirs:
    - test
    dependencies:
    - hspec
    - hspec-core
    - dropbox
    - aeson-qq
