name:                dropbox-client
version:             0.0.0
license:             MIT
author:              "Riskbook"
maintainer:          "support@riskbook.com"
copyright:           "2020 Riskbook"
github:              "riskbook/dropbox-client"

extra-source-files:
- Readme.md
- LICENSE
- Changelog.md

ghc-options:
    - -Wall
    - -Wcompat
    - -Wincomplete-uni-patterns
    - -Wredundant-constraints
    - -Wincomplete-record-updates
    - -Widentities

dependencies:
- base >= 4.7 && < 5
- servant-client-core
- servant-client
- servant-auth
- servant-auth-client
- http-api-data
- aeson
- servant
- http-client-tls
- text

library:
  source-dirs: src

executables:
  exe:
    main:                exe.hs
    source-dirs:         app
    dependencies:
    - dropbox-client
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N

tests:
  unit:
    main:                Spec.hs
    source-dirs:
    - test
    dependencies:
    - hspec
    - hspec-core
    - dropbox-client
    - aeson-qq
